# Generated by Django 3.1.5 on 2021-01-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_body', models.TextField()),
                ('blog_image', models.ImageField(upload_to='')),
                ('blog_created_on', models.DateTimeField(auto_now_add=True)),
                ('blog_last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
